import type * as Components from "kui-vue";

type Assert<T extends true> = T;
type TypedHandler<T> =
  NonNullable<T> extends (...args: infer Args) => unknown
    ? 0 extends 1 & Args[number]
      ? false
      : true
    : false;

// Every public emit must survive component wrappers and generic constructor casts.
export type PublicEventContract = [
  Assert<TypedHandler<InstanceType<typeof Components.Popup>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Popup>["$props"]["onUpdate:open"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Popup>["$props"]["onAfterOpen"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Popup>["$props"]["onAfterClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Affix>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Alert>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Anchor>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Anchor>["$props"]["onClick"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.AutoComplete>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.AutoComplete>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.AutoComplete>["$props"]["onClear"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.AutoComplete>["$props"]["onSearch"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.AutoComplete>["$props"]["onSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.AutoComplete>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.BackTop>["$props"]["onClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.BackTop>["$props"]["onVisibleChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.BreadcrumbItem>["$props"]["onClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Calendar>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Calendar>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Calendar>["$props"]["onMonthChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Calendar>["$props"]["onEventClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Carousel>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Carousel>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Cascader>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Cascader>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Cascader>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Cascader>["$props"]["onExpandChange"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.CheckCardGroup>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.CheckCardGroup>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.CheckCard>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.CheckCard>["$props"]["onChange"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.CheckboxGroup>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.CheckboxGroup>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Checkbox>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Checkbox>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Checkbox>["$props"]["onUpdate:checked"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.CollapsePanel>["$props"]["onExpand"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Collapse>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Collapse>["$props"]["onUpdate:openKeys"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.ColorPicker>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.ColorPicker>["$props"]["onUpdate:mode"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ColorPicker>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ColorPicker>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePicker>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePicker>["$props"]["onUpdate:startDate"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePicker>["$props"]["onUpdate:endDate"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePicker>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePicker>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePicker>["$props"]["onClear"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Drawer>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Drawer>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Drawer>["$props"]["onOk"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Drawer>["$props"]["onCancel"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Drawer>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DropdownButton>["$props"]["onClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Dropdown>["$props"]["onUpdate:show"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Dropdown>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.FeatureCard>["$props"]["onClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Form>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Form>["$props"]["onReset"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Form>["$props"]["onSubmit"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Icon>["$props"]["onClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Image>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Image>["$props"]["onSwitch"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Input>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Input>["$props"]["onSearch"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Input>["$props"]["onIconClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Input>["$props"]["onClear"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Input>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Input>["$props"]["onFocus"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Input>["$props"]["onBlur"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TextArea>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TextArea>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TextArea>["$props"]["onInput"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.InputNumber>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.InputNumber>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputNumber>["$props"]["onBlur"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputNumber>["$props"]["onKeydown"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputOTP>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputOTP>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputOTP>["$props"]["onComplete"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputOTP>["$props"]["onFocus"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputOTP>["$props"]["onBlur"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputTag>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputTag>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputTag>["$props"]["onAdd"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputTag>["$props"]["onRemove"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.InputTag>["$props"]["onClear"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Kanban>["$props"]["onMove"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Kanban>["$props"]["onItemClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Mentions>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Mentions>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Mentions>["$props"]["onSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Mentions>["$props"]["onSearch"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Mentions>["$props"]["onClear"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.MenuItem>["$props"]["onClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Menu>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Menu>["$props"]["onUpdate:openKeys"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Menu>["$props"]["onSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Menu>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Modal>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Modal>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Modal>["$props"]["onOk"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Modal>["$props"]["onCancel"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Modal>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Page>["$props"]["onUpdate:page"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Page>["$props"]["onUpdate:pageSize"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Page>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Popconfirm>["$props"]["onUpdate:show"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Popconfirm>["$props"]["onOk"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Popconfirm>["$props"]["onCancel"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Poptip>["$props"]["onUpdate:show"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Poptip>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.QRCode>["$props"]["onRefresh"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.RadioButton>["$props"]["onChange"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.RadioButton>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.RadioButton>["$props"]["onUpdate:checked"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.RadioGroup>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.RadioGroup>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Radio>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Radio>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Radio>["$props"]["onUpdate:checked"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Rate>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Rate>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Segmented>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Segmented>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Option>["$props"]["onClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Option>["$props"]["onMouseenter"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Option>["$props"]["onSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Select>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Select>["$props"]["onSearch"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Select>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Select>["$props"]["onSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Select>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Select>["$props"]["onClear"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Slider>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Slider>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Splitter>["$props"]["onResize"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Splitter>["$props"]["onResizeStart"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Splitter>["$props"]["onResizeEnd"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Steps>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Switch>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Switch>["$props"]["onUpdate:checked"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Switch>["$props"]["onChange"]>>,
  Assert<
    TypedHandler<
      InstanceType<typeof Components.TableColumnSetting>["$props"]["onUpdate:hiddenKeys"]
    >
  >,
  Assert<TypedHandler<InstanceType<typeof Components.TableColumnSetting>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onUpdate:selectedKeys"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onUpdate:expandedKeys"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onSort"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onRowClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onSelectAll"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onExpand"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Table>["$props"]["onExpandedKeysChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tabs>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tabs>["$props"]["onTabClick"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tabs>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tabs>["$props"]["onRemove"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tag>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tooltip>["$props"]["onUpdate:show"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tour>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tour>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tour>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tour>["$props"]["onFinish"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Transfer>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Transfer>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Transfer>["$props"]["onSearch"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Transfer>["$props"]["onSelectChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onUpdate:expandedKeys"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onUpdate:checkedKeys"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onUpdate:selectedKeys"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onExpand"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onCheck"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onDragstart"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onDragenter"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onDragleave"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onDrop"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onLoadError"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Tree>["$props"]["onDragend"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onUpdate:modelValue"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onUpdate:treeExpandedKeys"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onTreeSelect"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onSearch"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onTreeExpand"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TreeSelect>["$props"]["onClear"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onUpdate:fileList"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onRemove"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onSelectFiles"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onExceed"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onSizeError"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onTypeError"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Upload>["$props"]["onSort"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.VirtualList>["$props"]["onScroll"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.DatePickerPanel>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<
    TypedHandler<InstanceType<typeof Components.DatePickerPanel>["$props"]["onUpdate:startDate"]>
  >,
  Assert<
    TypedHandler<InstanceType<typeof Components.DatePickerPanel>["$props"]["onUpdate:endDate"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.DatePickerPanel>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePickerPanel>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.DatePickerPanel>["$props"]["onClear"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.ColorPickerPanel>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.ColorPickerPanel>["$props"]["onUpdate:mode"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ColorPickerPanel>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ColorPickerPanel>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ModalPanel>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ModalPanel>["$props"]["onOpenChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ModalPanel>["$props"]["onOk"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ModalPanel>["$props"]["onCancel"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.ModalPanel>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.PoptipPanel>["$props"]["onUpdate:show"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.PoptipPanel>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.PopconfirmPanel>["$props"]["onUpdate:show"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.PopconfirmPanel>["$props"]["onOk"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.PopconfirmPanel>["$props"]["onCancel"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TooltipPanel>["$props"]["onUpdate:show"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.MessagePanel>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.NoticePanel>["$props"]["onClose"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Typography>["$props"]["onUpdate:modelValue"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Typography>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.Typography>["$props"]["onCopy"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.TypographyText>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.TypographyText>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TypographyText>["$props"]["onCopy"]>>,
  Assert<
    TypedHandler<InstanceType<typeof Components.TypographyTitle>["$props"]["onUpdate:modelValue"]>
  >,
  Assert<TypedHandler<InstanceType<typeof Components.TypographyTitle>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TypographyTitle>["$props"]["onCopy"]>>,
  Assert<
    TypedHandler<
      InstanceType<typeof Components.TypographyParagraph>["$props"]["onUpdate:modelValue"]
    >
  >,
  Assert<TypedHandler<InstanceType<typeof Components.TypographyParagraph>["$props"]["onChange"]>>,
  Assert<TypedHandler<InstanceType<typeof Components.TypographyParagraph>["$props"]["onCopy"]>>,
];
