import './alert/styles';
import './affix/styles';
import './badge/styles';
import './backtop/styles';
import './breadcrumb/styles';
import './button/styles';
import './card/styles';
import './colorpicker/styles';
import './collapse/styles';
import './carousel/styles';
import './checkbox/styles';
// import './datepicker/styles/calendar.less';
// import './datepicker/styles/datepicker';
import './drawer/styles';
import './dropdown/styles';
import './form/styles';
import './icon/styles';
import './grid/styles';
import './input/styles';
import './imagepreview/styles';
import './loading/styles';
import './layout/styles';
import './modal/styles';
import './message/styles';
import './message/styles';
import './menu/styles';
import './notice/styles';
import './page/styles';
import './poptip/styles';
import './radio/styles';
// import './scroll/scroll';
import './select/styles';
import './switch/styles';
// import './slider/slider';
import './steps/styles';
import './timeline/styles';
import './tag/styles';
import './tooltip/styles';
import './table/styles';
import './tree/styles';
import './treeselect/styles';
import './tabs/styles';
import './upload/styles';