import "@vue/runtime-core";
import * as Comps from "../components/index.ts";

declare module "vue" {
  export interface GlobalComponents {
    AutoComplete: (typeof Comps)["AutoComplete"];
    Affix: (typeof Comps)["Affix"];
    Alert: (typeof Comps)["Alert"];
    Anchor: (typeof Comps)["Anchor"];
    AnchorLink: (typeof Comps)["AnchorLink"];
    Avatar: (typeof Comps)["Avatar"];
    AvatarGroup: (typeof Comps)["AvatarGroup"];
    Breadcrumb: (typeof Comps)["Breadcrumb"];
    BreadcrumbItem: (typeof Comps)["BreadcrumbItem"];
    BackTop: (typeof Comps)["BackTop"];
    Badge: (typeof Comps)["Badge"];
    Button: (typeof Comps)["Button"];
    KButton: (typeof Comps)["Button"];
    ButtonGroup: (typeof Comps)["ButtonGroup"];
    Card: (typeof Comps)["Card"];
    CardMeta: (typeof Comps)["CardMeta"];
    Cascader: (typeof Comps)["Cascader"];
    Carousel: (typeof Comps)["Carousel"];
    CarouselItem: (typeof Comps)["CarouselItem"];
    Checkbox: (typeof Comps)["Checkbox"];
    CheckboxGroup: (typeof Comps)["CheckboxGroup"];
    CheckCard: (typeof Comps)["CheckCard"];
    CheckCardGroup: (typeof Comps)["CheckCardGroup"];
    Collapse: (typeof Comps)["Collapse"];
    CollapsePanel: (typeof Comps)["CollapsePanel"];
    ColorPicker: (typeof Comps)["ColorPicker"];
    ColorPickerPanel: (typeof Comps)["ColorPickerPanel"];
    DatePicker: (typeof Comps)["DatePicker"];
    DatePickerPanel: (typeof Comps)["DatePickerPanel"];
    Descriptions: (typeof Comps)["Descriptions"];
    DescriptionsItem: (typeof Comps)["DescriptionsItem"];
    Drawer: (typeof Comps)["Drawer"];
    Dropdown: (typeof Comps)["Dropdown"];
    DropdownButton: (typeof Comps)["DropdownButton"];
    Divider: (typeof Comps)["Divider"];
    Empty: (typeof Comps)["Empty"];
    Form: (typeof Comps)["Form"];
    FormItem: (typeof Comps)["FormItem"];
    Flex: (typeof Comps)["Flex"];
    FlameWrap: (typeof Comps)["FlameWrap"];
    Grid: (typeof Comps)["Grid"];
    GridItem: (typeof Comps)["GridItem"];
    Image: (typeof Comps)["Image"];
    KImage: (typeof Comps)["Image"];
    ImageGroup: (typeof Comps)["ImageGroup"];
    Icon: (typeof Comps)["Icon"];
    Input: (typeof Comps)["Input"];
    InputTag: (typeof Comps)["InputTag"];
    InputGroup: (typeof Comps)["InputGroup"];
    InputOTP: (typeof Comps)["InputOTP"];
    TextArea: (typeof Comps)["TextArea"];
    InputNumber: (typeof Comps)["InputNumber"];
    Content: (typeof Comps)["Content"];
    Footer: (typeof Comps)["Footer"];
    Header: (typeof Comps)["Header"];
    Layout: (typeof Comps)["Layout"];
    Sider: (typeof Comps)["Sider"];
    Mentions: (typeof Comps)["Mentions"];
    Menu: (typeof Comps)["Menu"];
    MenuDivider: (typeof Comps)["MenuDivider"];
    MenuGroup: (typeof Comps)["MenuGroup"];
    MenuItem: (typeof Comps)["MenuItem"];
    SubMenu: (typeof Comps)["SubMenu"];
    Modal: (typeof Comps)["Modal"];
    ModalPanel: (typeof Comps)["ModalPanel"];
    MessagePanel: (typeof Comps)["MessagePanel"];
    NoticePanel: (typeof Comps)["NoticePanel"];
    Page: (typeof Comps)["Page"];
    Poptip: (typeof Comps)["Poptip"];
    PoptipPanel: (typeof Comps)["PoptipPanel"];
    Popconfirm: (typeof Comps)["Popconfirm"];
    PopconfirmPanel: (typeof Comps)["PopconfirmPanel"];
    Progress: (typeof Comps)["Progress"];
    QRCode: (typeof Comps)["QRCode"];
    Radio: (typeof Comps)["Radio"];
    Ripple: (typeof Comps)["Ripple"];
    RadioButton: (typeof Comps)["RadioButton"];
    RadioGroup: (typeof Comps)["RadioGroup"];
    Rate: (typeof Comps)["Rate"];
    Result: (typeof Comps)["Result"];
    Option: (typeof Comps)["Option"];
    Select: (typeof Comps)["Select"];
    ConfigProvider: (typeof Comps)["ConfigProvider"];
    Skeleton: (typeof Comps)["Skeleton"];
    SkeletonAvatar: (typeof Comps)["SkeletonAvatar"];
    SkeletonButton: (typeof Comps)["SkeletonButton"];
    SkeletonImage: (typeof Comps)["SkeletonImage"];
    SkeletonText: (typeof Comps)["SkeletonText"];
    StatCard: (typeof Comps)["StatCard"];
    FeatureCard: (typeof Comps)["FeatureCard"];
    FeedbackPanel: (typeof Comps)["FeedbackPanel"];
    StatNumber: (typeof Comps)["StatNumber"];
    Slider: (typeof Comps)["Slider"];
    Space: (typeof Comps)["Space"];
    Splitter: (typeof Comps)["Splitter"];
    SplitterPanel: (typeof Comps)["SplitterPanel"];
    Spin: (typeof Comps)["Spin"];
    Steps: (typeof Comps)["Steps"];
    Switch: (typeof Comps)["Switch"];
    KSwitch: (typeof Comps)["Switch"];
    Table: (typeof Comps)["Table"];
    Tooltip: (typeof Comps)["Tooltip"];
    TooltipPanel: (typeof Comps)["TooltipPanel"];
    TabPanel: (typeof Comps)["TabPanel"];
    Tabs: (typeof Comps)["Tabs"];
    TimeLine: (typeof Comps)["TimeLine"];
    TimeLineItem: (typeof Comps)["TimeLineItem"];
    Tree: (typeof Comps)["Tree"];
    TreeSelect: (typeof Comps)["TreeSelect"];
    Tag: (typeof Comps)["Tag"];
    Tour: (typeof Comps)["Tour"];
    Transfer: (typeof Comps)["Transfer"];
    Typography: (typeof Comps)["Typography"];
    TypographyText: (typeof Comps)["TypographyText"];
    TypographyParagraph: (typeof Comps)["TypographyParagraph"];
    TypographyTitle: (typeof Comps)["TypographyTitle"];
    Col: (typeof Comps)["Col"];
    Row: (typeof Comps)["Row"];
    Upload: (typeof Comps)["Upload"];
    Watermark: (typeof Comps)["Watermark"];
  }
}

declare module "*.less" {
  const content: { [className: string]: string };
  export default content;
}

export {};
