import "@vue/runtime-core";
import * as Comps from "../components/index.ts";

declare module "vue" {
  export interface GlobalComponents {
    Affix: (typeof Comps)["Affix"];
    Alert: (typeof Comps)["Alert"];
    Anchor: (typeof Comps)["Anchor"];
    AnchorLink: (typeof Comps)["AnchorLink"];
    Avatar: (typeof Comps)["Avatar"];
    AvatarGroup: (typeof Comps)["AvatarGroup"];
    Breadcrumb: (typeof Comps)["Breadcrumb"];
    BreadcrumbItem: (typeof Comps)["BreadcrumbItem"];
    BackTop: (typeof Comps)["BackTop"];
    Badge: (typeof Comps)["Badge"];
    Button: (typeof Comps)["Button"];
    ButtonGroup: (typeof Comps)["ButtonGroup"];
    Card: (typeof Comps)["Card"];
    Carousel: (typeof Comps)["Carousel"];
    CarouselItem: (typeof Comps)["CarouselItem"];
    Checkbox: (typeof Comps)["Checkbox"];
    CheckboxGroup: (typeof Comps)["CheckboxGroup"];
    Collapse: (typeof Comps)["Collapse"];
    CollapsePanel: (typeof Comps)["CollapsePanel"];
    ColorPicker: (typeof Comps)["ColorPicker"];
    DatePicker: (typeof Comps)["DatePicker"];
    Descriptions: (typeof Comps)["Descriptions"];
    DescriptionsItem: (typeof Comps)["DescriptionsItem"];
    Drawer: (typeof Comps)["Drawer"];
    Dropdown: (typeof Comps)["Dropdown"];
    DropdownButton: (typeof Comps)["DropdownButton"];
    Divider: (typeof Comps)["Divider"];
    Empty: (typeof Comps)["Empty"];
    Form: (typeof Comps)["Form"];
    FormItem: (typeof Comps)["FormItem"];
    Flex: (typeof Comps)["Flex"];
    Grid: (typeof Comps)["Grid"];
    GridItem: (typeof Comps)["GridItem"];
    ImageGroup: (typeof Comps)["ImageGroup"];
    KImage: (typeof Comps)["KImage"];
    Icon: (typeof Comps)["Icon"];
    Input: (typeof Comps)["Input"];
    InputGroup: (typeof Comps)["InputGroup"];
    TextArea: (typeof Comps)["TextArea"];
    InputNumber: (typeof Comps)["InputNumber"];
    Content: (typeof Comps)["Content"];
    Footer: (typeof Comps)["Footer"];
    Header: (typeof Comps)["Header"];
    Layout: (typeof Comps)["Layout"];
    Sider: (typeof Comps)["Sider"];
    Menu: (typeof Comps)["Menu"];
    MenuDivider: (typeof Comps)["MenuDivider"];
    MenuGroup: (typeof Comps)["MenuGroup"];
    MenuItem: (typeof Comps)["MenuItem"];
    SubMenu: (typeof Comps)["SubMenu"];
    Modal: (typeof Comps)["Modal"];
    Page: (typeof Comps)["Page"];
    Poptip: (typeof Comps)["Poptip"];
    Popconfirm: (typeof Comps)["Popconfirm"];
    Progress: (typeof Comps)["Progress"];
    Radio: (typeof Comps)["Radio"];
    RadioButton: (typeof Comps)["RadioButton"];
    RadioGroup: (typeof Comps)["RadioGroup"];
    Rate: (typeof Comps)["Rate"];
    Option: (typeof Comps)["Option"];
    Select: (typeof Comps)["Select"];
    ConfigProvider: (typeof Comps)["ConfigProvider"];
    Skeleton: (typeof Comps)["Skeleton"];
    SkeletonAvatar: (typeof Comps)["SkeletonAvatar"];
    SkeletonButton: (typeof Comps)["SkeletonButton"];
    SkeletonImage: (typeof Comps)["SkeletonImage"];
    SkeletonText: (typeof Comps)["SkeletonText"];
    StatCard: (typeof Comps)["StatCard"];
    StatNumber: (typeof Comps)["StatNumber"];
    Slider: (typeof Comps)["Slider"];
    Space: (typeof Comps)["Space"];
    Spin: (typeof Comps)["Spin"];
    KSwitch: (typeof Comps)["KSwitch"];
    Table: (typeof Comps)["Table"];
    Tooltip: (typeof Comps)["Tooltip"];
    TabPanel: (typeof Comps)["TabPanel"];
    Tabs: (typeof Comps)["Tabs"];
    TimeLine: (typeof Comps)["TimeLine"];
    TimeLineItem: (typeof Comps)["TimeLineItem"];
    Tree: (typeof Comps)["Tree"];
    TreeSelect: (typeof Comps)["TreeSelect"];
    Tag: (typeof Comps)["Tag"];
    Col: (typeof Comps)["Col"];
    Row: (typeof Comps)["Row"];
    Upload: (typeof Comps)["Upload"];
  }
}

export {};
