import {
  AlignHorizontalDistributeCenter,
  Anchor,
  AppWindow,
  AppWindowMac,
  ArrowDownNarrowWide,
  ArrowUpToLine,
  Badge,
  BetweenVerticalEnd,
  Calendar,
  ChartColumnDecreasing,
  ChevronRight,
  CircleCheck,
  CirclePlay,
  Columns3,
  Component,
  CreditCard,
  DecimalsArrowRight,
  FileText,
  FolderTree,
  Form,
  GalleryHorizontal,
  Gauge,
  Heart,
  Image,
  Inbox,
  Info,
  Languages,
  LayoutDashboard,
  List,
  ListChevronsUpDown,
  ListCollapse,
  Loader,
  Loading,
  Menu,
  MessageCircleCheck,
  MessageCircleMore,
  MessageSquareMore,
  Minus,
  MountainSnow,
  PaintBucket,
  Palette,
  PanelLeftClose,
  PanelsTopLeft,
  Pin,
  RectangleEllipsis,
  RectangleHorizontal,
  Settings2,
  SmilePlus,
  SquareCheck,
  SquareChevronRight,
  SquareDashedText,
  SquareMousePointer,
  Star,
  Table,
  Tag,
  TextAlignStart,
  ToggleLeft,
  TriangleAlert,
  Upload,
} from "kui-icons";
const navData = [
  {
    title: "menu.start",
    key: "guide",
    children: [
      {
        title: "快速开始",
        sub: "Quick Started",
        name: "quick-started",
        icon: CirclePlay,
      },
      {
        title: "在Nuxt中使用",
        sub: "Usage With Nuxt",
        name: "usage-with-nuxt",
        icon: MountainSnow,
      },
      {
        title: "国际化",
        sub: "Multilingual",
        name: "language",
        icon: Languages,
      },
      { title: "更新日志", sub: "Change Log", name: "change-log", icon: FileText },
      // { title: "定制主题", sub: "Themes", name: "theme", icon: "theme" },
      { title: "暗色模式", sub: "Dark Mode", name: "dark-mode", icon: PaintBucket },
      {
        title: "组件总览",
        sub: "All Components",
        name: "components",
        icon: Component,
      },
    ],
  },
  {
    title: "menu.universal",
    key: "basic",
    children: [
      { title: "按钮", sub: "Button", name: "button", icon: SquareMousePointer },
      { title: "图标", sub: "Icon", name: "icon", icon: Heart },
    ],
  },
  {
    title: "menu.layout",
    key: "layouts",
    children: [
      { title: "分割线", sub: "Divider", name: "divider", icon: Minus },
      { title: "弹性布局", sub: "Flex", name: "flex", icon: AlignHorizontalDistributeCenter },
      { title: "栅格", sub: "Row Col", name: "row-col", icon: Columns3 },
      { title: "网格", sub: "Grid", name: "grid", icon: LayoutDashboard },
      { title: "布局", sub: "Layout", name: "layout", icon: PanelsTopLeft },
      { title: "间距", sub: "Space", name: "space", icon: BetweenVerticalEnd },
    ],
  },
  {
    title: "menu.navigation",
    key: "navigation",
    children: [
      { title: "锚点", sub: "Anchor", name: "anchor", icon: Anchor },
      { title: "图钉", sub: "Affix", name: "affix", icon: Pin },
      {
        title: "面包屑",
        sub: "Breadcrumb",
        name: "breadcrumb",
        icon: ChevronRight,
      },
      {
        title: "下拉菜单",
        sub: "Dropdown",
        name: "dropdown",
        icon: ArrowDownNarrowWide,
      },
      { title: "导航菜单", sub: "Menu", name: "menu", icon: Menu },
      { title: "分页", sub: "Page", name: "page", icon: SquareChevronRight },
      // { title: "步骤条", sub: "Steps", name: "steps", icon: 'done-all' },
      { title: "标签页", sub: "Tabs", name: "tabs", icon: AppWindow },
      { title: "回到顶部", sub: "BackTop", name: "back-top", icon: ArrowUpToLine },
    ],
  },
  {
    title: "menu.form",
    key: "forms",
    children: [
      { title: "输入框", sub: "Input", name: "input", icon: RectangleHorizontal },
      {
        title: "数字输入框",
        sub: "InputNumber",
        name: "input-number",
        icon: DecimalsArrowRight,
      },
      { title: "多选框", sub: "Checkbox", name: "checkbox", icon: SquareCheck },
      { title: "单选框", sub: "Radio", name: "radio", icon: CircleCheck },
      { title: "开关", sub: "Switch", name: "switch", icon: ToggleLeft },
      { title: "选择器", sub: "Select", name: "select", icon: ListChevronsUpDown },
      {
        title: "树选择器",
        sub: "TreeSelect",
        name: "tree-select",
        icon: FolderTree,
      },
      {
        title: "日期选择框",
        sub: "DatePicker",
        name: "date-picker",
        icon: Calendar,
      },
      { title: "上传", sub: "Upload", name: "upload", icon: Upload },
      { title: "滑动输入条", sub: "Slider", name: "slider", icon: Settings2 },
      { title: "表单", sub: "Form", name: "form", icon: Form },
    ],
  },
  {
    title: "menu.data",
    key: "data",
    children: [
      { title: "头像", sub: "Avatar", name: "avatar", icon: SmilePlus },
      { title: "卡片", sub: "Card", name: "card", icon: CreditCard },
      { title: "走马灯", sub: "Carousel", name: "carousel", icon: GalleryHorizontal },
      {
        title: "折叠面板",
        sub: "Collapse",
        name: "collapse",
        icon: ListCollapse,
      },
      {
        title: "描述列表",
        sub: "Descriptions",
        name: "descriptions",
        icon: SquareDashedText,
      },
      { title: "图片", sub: "Image", name: "image", icon: Image },
      {
        title: "统计卡片",
        sub: "StatCard",
        name: "stat-card",
        icon: ChartColumnDecreasing,
      },
      { title: "表格", sub: "Table", name: "table", icon: Table },
      { title: "时间轴", sub: "TimeLine", name: "time-line", icon: List },
      { title: "树形控件", sub: "Tree", name: "tree", icon: FolderTree },
      // { title: "树选择", sub: "TreeSelect", name: "treeselect", icon: 'git-pull-request' },
    ],
  },
  {
    title: "menu.notice",
    key: "notices",
    children: [
      { title: "警告提示", sub: "Alert", name: "alert", icon: TriangleAlert },
      { title: "徽标", sub: "Badge", name: "badge", icon: Badge },
      { title: "抽屉", sub: "Drawer", name: "drawer", icon: PanelLeftClose },
      { title: "空状态", sub: "Empty", name: "empty", icon: Inbox },
      { title: "全局提示", sub: "Message", name: "message", icon: RectangleEllipsis },
      { title: "通知提醒", sub: "Notice", name: "notice", icon: Info },
      { title: "对话框", sub: "Modal", name: "modal", icon: AppWindowMac },
      { title: "气泡卡片", sub: "Poptip", name: "poptip", icon: MessageCircleMore },
      {
        title: "气泡确认框",
        sub: "Popconfirm",
        name: "popconfirm",
        icon: MessageCircleCheck,
      },
      { title: "评分", sub: "Rate", name: "rate", icon: Star },
      { title: "骨架屏", sub: "Skeleton", name: "skeleton", icon: TextAlignStart },
      { title: "加载中", sub: "Spin", name: "spin", icon: Loader },
      { title: "进度条", sub: "Progress", name: "progress", icon: Gauge },
      { title: "进度", sub: "Loading", name: "loading", icon: Loading },
      { title: "标签", sub: "Tag", name: "tag", icon: Tag },
      { title: "文字提示", sub: "Tooltip", name: "tooltip", icon: MessageSquareMore },
    ],
  },
  {
    title: "menu.other",
    key: "other",
    children: [
      {
        title: "颜色",
        sub: "ColorPicker",
        name: "color-picker",
        icon: Palette,
      },
    ],
  },
];

const routeData = navData.reduce((current: any[], { key, children }) => {
  current.push(...children);
  children.map((x: any) => (x.key = key));
  return current;
}, []);
export { navData, routeData };
